url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Trans Formations Project - GitHub Page" # the name of your site, e.g. ACME Corp.
description: "Together, we can resist anti-trans legislation."
